### PR TITLE
Update minitft_featherwing.py

### PR DESCRIPTION
**Pull request by hexthat**
I was having issues with the backlight setter when adding or subtracting from it for like a backlight fading effect.

### CODE REVIEW

**Comment by makermelissa** [comment]
The brightness setting should be a float between 0-1 and return that, but internally should map between 0-255. This PR appears to be a breaking change.

**Comment by hexthat** [comment]
this is version im using and it works fine
https://github.com/hexthat/minitft_featherwing/blob/master/minitft_featherwing.py

```
from minitft_featherwing import wing

wing.backlight = 254

while True:

	if wing.backlight > 255:

		wing.backlight = 0

	wing.backlight += 1
```

**Comment by makermelissa** [comment]
Maybe something more like this to work with the current version:
```
from minitft_featherwing import wing

wing.backlight = 1
while True:
	if wing.backlight > 1:
		wing.backlight = 0
	wing.backlight += 0.01
```

**Comment by hexthat** [comment]
hmm i didnt try 0.01 but i tried 0.1 and it wouldnt work

**Comment by makermelissa** [comment]
We probably need to add some notes to the code so it's more obvious about the intended range.

**Comment by hexthat** [comment]
I just tested it again and its working, other then when i try to send commands to seesaw too fast.

**Pull request closed without merging**
