### PR TITLE
Updating HT16K33 code to work with version 4.0.0

### PR DESCRIPTION
**Pull request by makermelissa**
The latest release of the HT16K33 library changes the brightness range from 0-15 to 0-1.0. This will make it work with the latest release. It also fixes an issue from a recent update by a community member.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
Does this change also need to be made in [matrix_featherwing.py](https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/blob/master/adafruit_featherwing/matrix_featherwing.py). Also would it make sense at this point to change these to use 0 - 1.0 instead of 0-15 like the HT16K33 itself is now?

**Review by AndrewTribble — APPROVED** [review]
Yep, this worked for me.  Using the copy under the Adafruit repo I got the crash `ValueError: Brightness must be a decimal number in the range: 0.0-1.0` and switching to this version, that went away and now it runs.  Tested it using the `featherwing_alphanum_simpletest.py` example on a Feather nRF running CircuitPython build `20200321-7e56f6e` with one of these: https://www.adafruit.com/product/3129

**Comment by makermelissa** [comment]
Good catch @FoamyGuy. I updated it for the matrix featherwing as well.

**Comment by FoamyGuy** [comment]
I will test this with matrix featherwing this week and merge once testing is complete.

**Review by FoamyGuy — APPROVED** [review]
Tested successfully with PyGamer and 16x8 matrix featherwing using the fading portion of the simpletest in examples.

**Pull request merged**
