### PR TITLE
Added DS3231 RTC Featherwing

### PR DESCRIPTION
**Pull request by makermelissa**
Ok, the next FeatherWing is done. I added some cool features such as the ability to change individual numbers instead of the entire time/date structure as well as a few other goodies like checking number of days and getting/setting by unix time.

### CODE REVIEW

**Comment by jerryneedell** [comment]
I just tried a few things ona Particle Argon with the DS3231 Featherwing and ran into this - is something missing?
```>>> import time
>>> from adafruit_featherwing import rtc_featherwing
>>> days = ("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
>>>
>>> rtc = rtc_featherwing.RTCFeatherWing()
>>> rtc.unixtime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_featherwing/rtc_featherwing.py", line 292, in unixtime
AttributeError: 'module' object has no attribute 'mktime'
>>> rtc.now
DateTime(second=8, minute=21, hour=3, day=17, month=2, year=2019, weekday=0)
>>> 
```

**Comment by jerryneedell** [comment]
apparently 
```
>>> import time
>>> dir(time)
['__class__', '__name__', 'monotonic', 'sleep', 'struct_time']
>>> 
```

**Comment by makermelissa** [comment]
Oh, I wonder if the mktime() is board specific. I figured all of the time functionality was the same. I'll try on my argon and see what happens.

**Comment by makermelissa** [comment]
Well, it was more of a nicety, so I can just remove that function.

**Comment by jerryneedell** [comment]
but on the feather_m4 
```
ress any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.2-72-gf7a397d52 on 2019-02-16; Adafruit Feather M4 Express with samd51j19
>>> 
>>> import time
>>> dir(time)
['__class__', '__name__', 'localtime', 'mktime', 'monotonic', 'monotonic_ns', 'sleep', 'struct_time', 'time']
>>> 
```

**Comment by jerryneedell** [comment]
It is a nice thing to have -- I wonder how how hard it is to get mktime into the nrf builds

**Comment by makermelissa** [comment]
It has mktime on mine, but I'm running into some other oddities on the argon. It may or may not function with the ds3231 library itself. I'll try the nrf52840 express and see how that behaves.

**Comment by makermelissa** [comment]
Yeah, I'm getting the same oddities on the nRF52840 Express. Something about tm_sec not existing, so I'll see if I can get it working on that board as well as the feather m4 express.

**Comment by makermelissa** [comment]
Ok yeah, it looks like the bug is in the DS3231 library. I can't get that example to run either.

**Comment by jerryneedell** [comment]
you have mktime on your argon? that odd -- why don't I?

**Comment by makermelissa** [comment]
Yeah, probably because I compiled the bootloader for it myself.

**Comment by jerryneedell** [comment]
its not from the Bootloader -- its in CP  - what version of CP do you have?

**Comment by makermelissa** [comment]
4.0.0 Beta 2

**Comment by jerryneedell** [comment]
what build? this is current master for nrf52840 (actually yesterdays master) --  but it is the same now
```
ress any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.2-68-g619b4f13f on 2019-02-15; Adafruit Feather nRF52840 Express with nRF52840
>>> import time
>>> dir(time)
['__class__', '__name__', 'monotonic', 'sleep', 'struct_time']
>>> 
```

**Comment by makermelissa** [comment]
For Argon:
Adafruit CircuitPython 4.0.0-beta.2 on 2019-02-05; Particle Argon with nRF52840

For nRF52840:
Adafruit CircuitPython 4.0.0-beta.2 on 2019-02-05; Adafruit Feather nRF52840 Express with nRF52840

Both have mktime()

**Comment by jerryneedell** [comment]
hmmm -- must have gotten removed since then ...

**Comment by makermelissa** [comment]
Mine came from the releases tab off of github, yours appears to be compiled, but I could be wrong.

**Comment by jerryneedell** [comment]
yes - mine is built from the current master branch of the repo.

**Comment by jerryneedell** [comment]
this looks suspicious and it was part of the recent changes, I think
https://github.com/adafruit/circuitpython/blob/a345ef28f2278dd53a33d96861c0c7d3fad6fbbe/ports/nrf/mpconfigport.mk#L23

**Comment by makermelissa** [comment]
Yeah, I got a message about that when attempting to run localtime() on mine even though the functions are all there.
```
>>> import time
>>> time.localtime()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: RTC is not supported on this board
```

**Comment by jerryneedell** [comment]
AH -- they may have just been stubs. Not really implemented.

**Comment by makermelissa** [comment]
Oh, ok. That would explain the odd functionality.

**Comment by jerryneedell** [comment]
so -- is the "unixtime' getter/seterr the only issue on the nrf boards?

**Comment by dhalbert** [comment]
It's true there's no real rtc support in nrf yet. I turned it off for that reason, but it appears that there are helper functions needed by other stuff. Could you write this up as an issue for adafruit/circuitpython listing the specific missing functionality and I'll try to make it work again.

**Comment by makermelissa** [comment]
No. The DS3231 library will not work at all on NRF boards.

**Comment by makermelissa** [comment]
Thanks for chiming in Dan. Sure, I can write something up.

**Comment by jerryneedell** [comment]
I was able to read mine with rtc.now

**Comment by dhalbert** [comment]
But it is in process: https://github.com/adafruit/circuitpython/pull/1534

**Comment by jerryneedell** [comment]
BTW  -- Nice job on the library @makermelissa ! It makes the wing very easy to use! Thanks for creating it.

**Comment by makermelissa** [comment]
Ok, maybe there's some newer code that is addressing this functionality that hasn't been released.

**Comment by makermelissa** [comment]
Thanks Jerry. I'm aiming for code that's easy to use, but still very flexible and powerful.

**Comment by makermelissa** [comment]
Since we now know the issue is really at the level of the DS3231 library or possibly even lower than that, I'm not really sure what to do since fixing the actual problem should propagate the fix to this library.

**Comment by jerryneedell** [comment]
It is not clear to me if there is a fundamental problem on the nrf boards supporting this library In my test, only the unixtime getter/setter seem to be an issue -- is it likely they will also work with a little magic by @dhalbert . If not, perhaps a try/except should be added for them so they can fail more gracefully. I guess it is not clear to me how using this library is impacted by the "builtin" etc module being implemented.  Does that only impact the availability of mtkime/localtime?

**Comment by makermelissa** [comment]
I have added the try/except blocks as you suggested. Please try it again when you have some time (no pun intended). Thanks.

**Review by jerryneedell — APPROVED** [review]
I have no concerns with the library so I'll go ahead and approve. There are still issues to be resolved with the nrf52840 but they are understood and in work and I don't think there is any reason to hold this up.

**Pull request merged**
